// 演示 App 模块
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gjr.glassbutton.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.gjr.glassbutton.demo"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':glassbutton')
}
